version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks: 
      - master
    environment:
      - DATABASE_URL=postgresql://demo:demo@db:5432/demo
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=demo
      - POSTGRES_USER=demo
      - POSTGRES_DB=demo
    ports:
      - "5432:5432"
    networks: 
      - master

  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks: 
      - master
    depends_on:
      - db

networks:
  master: